:PROPERTIES:
:ID:       acdaaefc-3e5c-4bbb-bf05-40fe6de963c9
:ROAM_ALIASES: "The Fundamental Principle of Counting"
:END:
#+title: The Basic Principle of Counting
#+filetags: combinatorics counting

* Definition
Suppose that tasks \(T_1\) and \(T_2\) are to be performed in sequence.
If \(T_1\) can be performed in \(n\) ways, and for each of these ways \(T_2\) can be performed in \(m\) ways, then the [[id:d1a18e96-d26e-4ec0-85be-596c9d8a64a7][sequence]] \(T_1T_2\) can be performed in \(n_1n_2\) ways.

* In Probability
- Experiment 1: \(m\) outcomes
- Experiment 2: \(n\) outcomes
  => \(mn\) combined possible outcomes

\begin{array}{cccc}
(1, 1) & (1, 2) & \ldots & (1, n) \\
(2, 1) & (2, 2) & \ldots & (2, n) \\
\vdots & \vdots & \ddots & \vdots \\
(m, 1) & (m, 2) & \ldots & (m, n) \\
\end{array}

* Generalised Basic Principle
** In General
Suppose that tasks \(T_1, T_2, \ldots, T_k\) are to be performed in sequence.
If \(T_1\) can be performed in \(n_1\) ways, and for each of these ways \(T_2\) can be performed in \(n_2\) ways, and for each of these \(n_1 n_2\) ways of performing \(T_1 T_2\) in sequence, \(T_3\) can be performed in \(n_3\) ways, and so on, then the sequence \(T_1 T_2 \cdots T_k\) can be performed in exactly \(n_1 n_2 \cdots n_k\) ways.
** In Probability
If \(r\) experiments are performed such that the first one may result in any of \(n_{1}\) possible outcomes, there are \(n_2\) posible outcomes of the second experiment.
There is a total of \(n_1\cdot n_2\ldots n_{r}\) possible outcomes of the \(r\) experiments.

\(n_1\cdot n_2\cdots n_r= \prod_{i=1}^r n_{i}\)
